cloud_config:
    palettes:
      aqua: ['BED661', '89E894', '78D5E3', '7AF5F5', '34DDDD', '93E2D5']
      yellow_blue: ['FFCC00', 'CCCCCC', '666699']
      grey: ['87907D', 'AAB6A2', '555555', '666666']
      brown: ['CC6600', 'FFFBD0', 'FF9900', 'C13100']
      army: ['595F23', '829F53', 'A2B964', '5F1E02', 'E15417', 'FCF141']
      pastel: ['EF597B', 'FF6D31', '73B66B', 'FFCB18', '29A2C6']
      red: ['FFFF66', 'FFCC00', 'FF9900', 'FF0000']

    words:
        blacklist: [all,and,our,your,this,any,some,they,their,his,her,the,you,them,yours,with,such,even,have,was,when,most,into]
