palettes:
    Aqua: ['#BED661', '#89E894', '#78D5E3', '#7AF5F5', '#34DDDD', '#93E2D5']
    'Yellow Blue': ['#FFCC00', '#CCCCCC', '#666699']
    Grey: ['#87907D', '#AAB6A2', '#555555', '#666666']
    Brown: ['#CC6600', '#FFFBD0', '#FF9900', '#C13100']
    Army: ['#595F23', '#829F53', '#A2B964', '#5F1E02', '#E15417', '#FCF141']
    Pastel: ['#EF597B', '#FF6D31', '#73B66B', '#FFCB18', '#29A2C6']
    Red: ['#FFFF66', '#FFCC00', '#FF9900', '#FF0000']
    'Spring Grass': ['#bcd664', '#99c460', '#78b654', '#66ab4d', '#54a244']
    Facebook: ['#3b5998', '#8b9dc3', '#dfe3ee', '#f7f7f7', '#ffffff']
    'Princess Pink': ['#ffc2cd', '#ff93ac', '#ff6289', '#fc3468', '#ff084a']
    'Neon 0908': ['#fe0000', '#fdfe02', '#0bff01', '#011efe', '#fe00f6']
    Beach: ['#96ceb4', '#ffeead', '#ff6f69', '#ffcc5c', '#88d8b0']
    '24K GOLD': ['#a67c00', '#bf9b30', '#ffbf00', '#ffcf40', '#ffdc73']
    'Beautyful Blues': ['#011f4b', '#03396c', '#005b96', '#6497b1', '#b3cde0']
    'Skin Tones': ['#8d5524', '#c68642', '#e0ac69', '#f1c27d', '#ffdbac']
    'Metro UI': ['#d11141', '#00b159', '#00aedb', '#f37735', '#ffc425']
