<?php

namespace SixtyNine\CloudBundle\Repository;

/**
 * CloudWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CloudWordRepository extends \Doctrine\ORM\EntityRepository
{
}
