<?php

namespace SixtyNine\CloudBundle\Repository;
use SixtyNine\CloudBundle\Entity\WordsList;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWordsOrdered(WordsList $list, $sortBy, $order = 'ASC')
    {
        if (!in_array(strtoupper($order), array('ASC', 'DESC'))) {
            $order = 'ASC';
        }

        $qb = $this
            ->createQueryBuilder('w')
            ->andWhere('w.list = :list')
            ->setParameter('list', $list)
        ;

        switch (true) {
            case 'alpha' === $sortBy:
                $qb->addOrderBy('w.text', $order);
                break;
            case 'count' === $sortBy:
                $qb->addOrderBy('w.count', $order);
                break;
            case 'angle' === $sortBy:
                $qb->addOrderBy('w.orientation', $order);
                break;
            default:
                throw new BadRequestHttpException('Invalid sort order');
        }

        return $qb->getQuery()->execute();
    }
}
